version: "3.5"
services:
  spark-cluster:
    build:
      context: ./base
    image: datworks/spark
    command: echo "Dummy service"

  spark-master:
    container_name: spark-master
    image: datworks/spark
    expose:
      - 7077
    ports:
      - 7077:7077
      - 18081:18081
    command:
      - start-master.sh
    environment:
      SPARK_NO_DAEMONIZE: 1
      SERVICE_NAME: "spark-master"
      SPARK_PUBLIC_DNS: "localhost"
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 18081
    networks:
      - sparknet
    volumes:
      - ./events:/tmp/spark-events
      - /home/dat/output:/data

  spark-worker:
    container_name: "spark-worker"
    image: datworks/spark
    hostname: "spark-worker"
    command:
      - start-slave.sh
      - spark://spark-master:7077
    environment:
      GRANT_SUDO: 1
      SPARK_NO_DAEMONIZE: 1
      SERVIVE_NAME: "spark-worker"
      SPARK_USER: "root"
      SPARK_WORKER_CORES: 32
      SPARK_WORKER_MEMORY: 64g
      SPARK_WORKER_PORT: 18881
      SPARK_PUBLIC_DNS: localhost
      SPARK_WORKER_WEBUI_PORT: 18082
    links:
      - spark-master
      - livy
    expose:
      - 17012
      - 17013
      - 17014
      - 17015
      - 17016
      - 18881
    ports:
      - 18082  # put 18082:18082 only if single worker
    networks:
      - sparknet
    volumes:
     - ./events:/tmp/spark-events
     - /home/dat/output:/data

  livy:
    image: datworks/livy_server
    build:
      context: ./livy_server
    hostname: "livy"
    command: /apps/livy/bin/livy-server
    networks: 
      - sparknet
    expose: 
      - 8998
    ports: 
      - 8998:8998
    volumes:
     - /home/dat/output:/data

  jupyter:
    image: datworks/jupyter
    build:
      context: ./jupyter_notebook
    command:
      - jupyter
      - lab
      - --ip='0.0.0.0'
      - --port=8888
      - --NotebookApp.password='sha1:921891234e96:1c683847ddc326ec718f77a3626fc5310d08b858'
    links:
      - livy
    networks: 
      - sparknet
    ports: 
      - 8888:8888
    volumes:
     - /home/dat/notebook:/opt/notebooks

networks:
  sparknet: 

